auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/zoe/BEP-Zoe/book/tutorials_examples/1_HBV_Caravan_ERA5/esmvaltool_output/ewcrep2e4oppx0_20250514_142329/preproc/diagnostic/pr/metadata.yml
- /home/zoe/BEP-Zoe/book/tutorials_examples/1_HBV_Caravan_ERA5/esmvaltool_output/ewcrep2e4oppx0_20250514_142329/preproc/diagnostic/tas/metadata.yml
- /home/zoe/BEP-Zoe/book/tutorials_examples/1_HBV_Caravan_ERA5/esmvaltool_output/ewcrep2e4oppx0_20250514_142329/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/zoe/BEP-Zoe/book/tutorials_examples/1_HBV_Caravan_ERA5/esmvaltool_output/ewcrep2e4oppx0_20250514_142329/plots/diagnostic/script
recipe: ewcrep2e4oppx0.yml
run_dir: /home/zoe/BEP-Zoe/book/tutorials_examples/1_HBV_Caravan_ERA5/esmvaltool_output/ewcrep2e4oppx0_20250514_142329/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/zoe/BEP-Zoe/book/tutorials_examples/1_HBV_Caravan_ERA5/esmvaltool_output/ewcrep2e4oppx0_20250514_142329/work/diagnostic/script
