auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/zoe/BEP-Zoe/book/thesis_projects/BSc/2025_Q4_ZoeLucius_CEG/Practice notebook/esmvaltool_output/ewcrepfppy_12n_20250514_215933/preproc/diagnostic/pr/metadata.yml
- /home/zoe/BEP-Zoe/book/thesis_projects/BSc/2025_Q4_ZoeLucius_CEG/Practice notebook/esmvaltool_output/ewcrepfppy_12n_20250514_215933/preproc/diagnostic/tas/metadata.yml
- /home/zoe/BEP-Zoe/book/thesis_projects/BSc/2025_Q4_ZoeLucius_CEG/Practice notebook/esmvaltool_output/ewcrepfppy_12n_20250514_215933/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/zoe/BEP-Zoe/book/thesis_projects/BSc/2025_Q4_ZoeLucius_CEG/Practice
  notebook/esmvaltool_output/ewcrepfppy_12n_20250514_215933/plots/diagnostic/script
recipe: ewcrepfppy_12n.yml
run_dir: /home/zoe/BEP-Zoe/book/thesis_projects/BSc/2025_Q4_ZoeLucius_CEG/Practice
  notebook/esmvaltool_output/ewcrepfppy_12n_20250514_215933/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/zoe/BEP-Zoe/book/thesis_projects/BSc/2025_Q4_ZoeLucius_CEG/Practice
  notebook/esmvaltool_output/ewcrepfppy_12n_20250514_215933/work/diagnostic/script
