name: Validate copyright of images 🔍️

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-image-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python3 -m pip install https://github.com/eWaterCycle/copyright-checker/archive/refs/heads/main.zip
      - name: Check copyright
        run: check-copyright book/